name = "PredatorPreyTutorial"
uuid = "57f5783d-547e-4ee8-be84-f0d6b205fe81"
authors = ["Rajith Vidanaarachchi"]
version = "0.1.0"

[deps]
Agents = "46ada45e-f475-11e8-01d0-f70cc89e6671"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"

[compat]
CairoMakie = "0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
